INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(QUAT_INCLUDE_PATH quat.h)
FIND_LIBRARY(QUAT_LIBRARY_PATH quat)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(QUAT DEFAULT_MSG 
                                  QUAT_INCLUDE_PATH 
                                  QUAT_LIBRARY_PATH)

IF(QUAT_FOUND)
  SET(QUAT_INCLUDE_DIRS ${QUAT_INCLUDE_PATH})
  SET(QUAT_LIBRARIES ${QUAT_LIBRARY_PATH})
ENDIF(QUAT_FOUND)



