INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(GLOG_INCLUDE_PATH glog/logging.h)
FIND_LIBRARY(GLOG_LIBRARY_PATH glog)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLOG DEFAULT_MSG 
                                  GLOG_INCLUDE_PATH 
                                  GLOG_LIBRARY_PATH)

IF(GLOG_FOUND)
  SET(GLOG_INCLUDE_DIRS ${GLOG_INCLUDE_PATH})
  SET(GLOG_LIBRARIES ${GLOG_LIBRARY_PATH})
ENDIF(GLOG_FOUND)

