INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(VRPN_INCLUDE_PATH vrpn_Button.h)
FIND_LIBRARY(VRPN_LIBRARY_PATH vrpn)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(VRPN DEFAULT_MSG 
                                  VRPN_INCLUDE_PATH 
                                  VRPN_LIBRARY_PATH)

IF(VRPN_FOUND)
  SET(VRPN_INCLUDE_DIRS ${VRPN_INCLUDE_PATH})
  SET(VRPN_LIBRARIES ${VRPN_LIBRARY_PATH})
ENDIF(VRPN_FOUND)



