INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(GFLAGS_INCLUDE_PATH gflags/gflags.h)
FIND_LIBRARY(GFLAGS_LIBRARY_PATH gflags)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GFLAGS DEFAULT_MSG 
                                  GFLAGS_INCLUDE_PATH 
                                  GFLAGS_LIBRARY_PATH)

IF(GFLAGS_FOUND)
  SET(GFLAGS_INCLUDE_DIRS ${GFLAGS_INCLUDE_PATH})
  SET(GFLAGS_LIBRARIES ${GFLAGS_LIBRARY_PATH})
ENDIF(GFLAGS_FOUND)


